// Mock Leave Request Data
export const mockLeaveRequests = [
  {
    id: '1',
    requesterName: 'Aarav Kumar',
    requesterType: 'student',
    leaveType: 'Medical Issue',
    fromDate: '2026-04-20',
    toDate: '2026-04-22',
    subject: 'Medical Checkup',
    message: 'Need to attend medical appointment',
    status: 'pending',
  },
  {
    id: '2',
    requesterName: 'Mr. Rajesh Kumar',
    requesterType: 'teacher',
    leaveType: 'Vacation',
    fromDate: '2026-04-25',
    toDate: '2026-05-05',
    subject: 'Family Vacation',
    message: 'Annual family trip to hill station',
    status: 'pending',
  },
  {
    id: '3',
    requesterName: 'Bhavna Singh',
    requesterType: 'student',
    leaveType: 'Personal Work',
    fromDate: '2026-04-21',
    toDate: '2026-04-21',
    subject: 'Personal Work',
    message: 'Important family work',
    status: 'pending',
  },
  {
    id: '4',
    requesterName: 'Ms. Priya Sharma',
    requesterType: 'teacher',
    leaveType: 'Medical Issue',
    fromDate: '2026-04-23',
    toDate: '2026-04-24',
    subject: 'Surgery Recovery',
    message: 'Post-surgery rest required',
    status: 'pending',
  },
  {
    id: '5',
    requesterName: 'Chirag Patel',
    requesterType: 'student',
    leaveType: 'Planned Leave',
    fromDate: '2026-05-01',
    toDate: '2026-05-03',
    subject: 'Planned Leave',
    message: 'Prior planned leave',
    status: 'pending',
  },
  {
    id: '6',
    requesterName: 'Dr. Amit Singh',
    requesterType: 'teacher',
    leaveType: 'Other',
    fromDate: '2026-04-26',
    toDate: '2026-04-26',
    subject: 'Conference',
    message: 'Attending educational conference',
    status: 'pending',
  },
];
